---
arch: ppc64le
dist: focal
os: linux
language: shell

git:
  depth: false

services:
    - docker

before_install:
    - sudo apt install -y jq; jq --version
    - docker pull registry.access.redhat.com/ubi9/ubi:9.3


jobs:
  include:
    - stage: pr_builds
      name: "Create Wheel for Python 3.12"
      env: PYTHON_VERSION="3.12"
      before_script:
        - git fetch --all
        - chmod +x script/check_build_scripts.sh
        - script/check_build_scripts.sh
      script:
        - "In script block"