---
arch: ppc64le
dist: focal
os: linux
language: shell

services:
    - docker

before_install:
    - docker pull registry.access.redhat.com/ubi9/ubi:9.3

jobs:
  include:
    - stage: pr_builds
      name: "Create Wheel for Python 3.12"
      if: env(WHEEL_BUILD) = true
      env: PYTHON_VERSION="3.12"
      before_script:
        - |
          # Get the list of modified .sh files
          MODIFIED_FILES=$(git diff --name-only origin/main...HEAD -- '*.sh')

          if [[ -z "$MODIFIED_FILES" ]]; then
            echo "No build script modifications detected."
            exit 0
          fi

          for file in $MODIFIED_FILES; do
            PACKAGE_DIR=$(dirname "$file")
            BUILD_SCRIPT_PATH=$(realpath "$file")
            BUILD_INFO_FILE="$PACKAGE_DIR/build_info.json"

            if [[ -f "$BUILD_INFO_FILE" ]]; then
              VERSION=$(jq -r '.version' "$BUILD_INFO_FILE")
              echo "Build Script: $BUILD_SCRIPT_PATH"
              echo "Package Directory: $PACKAGE_DIR"
              echo "Version: $VERSION"
            else
              echo "Build Script: $BUILD_SCRIPT_PATH"
              echo "Package Directory: $PACKAGE_DIR"
              echo "No build_info.json found in $PACKAGE_DIR"
            fi
          done
      script:
        - echo "wheel build python 3.12"
        #- chmod +x ./script/build_wheels.sh; bash ./script/build_wheels.sh;
